### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tsuraan** [MostAwesomeDude/tiger#1]
I'm curious about tiger's license.  One file in the repo (tigermodule.c) says it's GPL3, but the rest of the library has no license notices, and the repo has no base LICENSE or COPYING file.

**Comment by infinity0** [comment]
The original tiger sources sboxes.c and tiger.c are directly from Eli Biham's reference implementation:

http://www.cs.technion.ac.il/~biham/Reports/Tiger/

He does not explicitly give terms for distribution, but the webpage says:

> Tiger has no usage restrictions nor patents. It can be used freely, with the reference implementation, with other implementations or with a modification to the reference implementation (as long as it still implements Tiger). We only ask you to let us know about your implementation and to cite the origin of Tiger and of the reference implementation.

There is also a `testtiger.c` that isn't included here, for some reason.

**Comment by MostAwesomeDude** [comment]
I will double-check that I am the sole author of any non-public-domain code, and amend the license accordingly.
